#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum preonic_layers {
  _BASE_QWERTY,
  _NUM_ROW_EXT,
  _MEDIA_BRACKETS
  _EXTRA,

  _LOWER,
  _RAISE,
  _ADJUST
};

// transparent and nop
#define KTR K_TRNS
#define KNO K_NO

// momentary
#define MO_LWR MO(_LOWER)
#define MO_RSE MO(_RAISE)
#define MO_ADJ MO(_ADJUST)
#define MO_EXT MO(_EXTRA)

// momentary when held
#define LT_NEXT LT(_NUM_ROW_EXT,KC_BSPC)
#define LT_MDIA LT(_MEDIA_BRACKETS,KC_BSLS)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[_BASE_QWERTY] = LAYOUT_ortho_5x12(
        KC_GESC, KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    LT_NEXT,
        KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    LT_MDIA,
        KC_GRV,  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_ENT,
        MO_EXT,  KC_LCTL, KC_LALT, KC_LGUI, MO_LWR,  KC_SPC,  KC_SPC,  MO_RSE,  KC_LEFT, KC_UP,   KC_DOWN, KC_RGHT
    ),

	[_MEDIA_BRACKETS] = LAYOUT_ortho_5x12(
        KTR,     KNO,     KNO,     KNO,     KNO,     KC_MRWD, KC_MPLY, KC_MFFD, KC_MUTE, KC_VOLD, KC_VOLU, KC_DEL,
        KTR,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KC_LBRC, KC_RBRC, KTR,    
        KTR,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KC_SCLN, KC_QUOT, KTR,    
        KTR,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KTR,    
        KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR
    ),

	[_NUM_ROW_EXT] = LAYOUT_ortho_5x12(
        KTR,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KC_MINS, KC_EQL,  KTR,    
        KTR,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KC_LBRC, KC_RBRC, KTR,    
        KTR,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KC_SCLN, KC_QUOT, KTR,    
        KTR,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KTR,    
        KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR
    ),

	[_EXTRA] = LAYOUT_ortho_5x12(
        KTR,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KC_MINS, KC_EQL,  KTR,    
        KTR,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KC_LBRC, KC_RBRC, KTR,    
        KTR,     KC_BTN1, KC_BTN2, KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KC_SCLN, KC_QUOT, KTR,    
        KTR,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     KNO,     RGB_TOG,
        KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     RGB_RMOD,RGB_VAI, RGB_VAD, RGB_MOD
    ),

	[_LOWER] = LAYOUT_ortho_5x12(
        KC_TILD, KC_EXLM, KC_AT,   KC_HASH, KC_F1,   KC_F2,   KC_F3,   KC_AMPR, KC_ASTR, KC_UNDS, KC_PLUS, KC_DEL,
        KC_BSPC, KC_EXLM, KC_UP,   KC_ENT,  KC_F4,   KC_F5,   KC_F6,   KC_AMPR, KC_ASTR, KC_LBRC, KC_RBRC, KC_BSPC,
        KC_DEL,  KC_LEFT, KC_DOWN, KC_RGHT, KC_F7,   KC_F8,   KC_F9,   KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, KC_PIPE,
        KTR,     KC_BTN1, KC_BTN2, KC_BTN3, KC_F10,  KC_F11,  KC_F12,  KNO,     KNO,     KC_VOLD, KC_VOLU, KTR,    
        KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     MO_ADJ,  KC_MNXT, KC_HOME, KC_END,  KC_MPLY
    ),

	[_RAISE] = LAYOUT_ortho_5x12(
        KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_MINS, KC_EQL,  KC_BSPC,
        KC_GRV,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    KC_7,    KC_8,    KC_LBRC, KC_RBRC, KC_DEL,
        KC_DEL,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_MINS, KC_EQL,  KC_SCLN, KC_QUOT, KTR,    
        KTR,     KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,  KC_NUHS, KC_NUBS, KC_VOLD, KC_VOLU, KTR,    
        KTR,     KTR,     KTR,     KTR,     MO_ADJ,  KTR,     KTR,     KTR,     KC_MNXT, KC_PGUP, KC_PGDN, KC_MPLY
    ),

	[_ADJUST] = LAYOUT_ortho_5x12(
        KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_F11,  KC_F12,
        KTR,     RESET,   DEBUG,   KTR,     KTR,     KTR,     KTR,     TERM_ON, TERM_OFF,KTR,     KTR,     KC_DEL,
        KTR,     KTR,     MU_MOD,  AU_ON,   AU_OFF,  AG_NORM, AG_SWAP, KNO,     KNO,     KNO,     KTR,     KTR,    
        KTR,     MUV_DE,  MUV_IN,  MU_ON,   MU_OFF,  MI_ON,   MI_OFF,  KTR,     KTR,     KTR,     KTR,     KTR,    
        KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR,     KTR
    )
};
